test:
  testing_servers : [ie7_windows, firefox_30_osx, firefox_windows, safari_404_osx, safari_404_windows]
  kobj_static_js_url: "http://static.kobj.net/kobj-static-20100513215959.js"
#  kobj_static_js_url: "http://init.kobj.net/js/shared/kobj-static.js"
 # New
#  kobj_static_js_url: "http://static.kobj.net/kobj-static-20100513165620.js"


  #kobj_static_js_url: "http://static.kobj.net/kobj-static-20100415065837.js"
#  kobj_static_js_url: "http://static.kobj.net/kobj-static-20100408173225.js"

firefox_30_osx :
  host : "office.kynetx.com"
  port : 4444
  browser : "*firefox"

safari_404_osx :
  host : "office.kynetx.com"
  port : 4444
  browser : "*safari"

safari_404_windows :
  host : "184.73.68.157"
  port : 4444
  browser : "*safari"


ie7_windows :
  host : "184.73.68.157"
  port : 4444
  browser : "*iexplore"


firefox_windows :
  host : "184.73.68.157"
  port : 4444
  browser : "*firefox"

chrome_beta_windows :
  host : "184.73.68.157"
  port : 4444
  browser : "*googlechrome"




#Supported browsers include:
#  *firefox
#  *mock
#  *firefoxproxy
#  *pifirefox
#  *chrome
#  *iexploreproxy
#  *iexplore
#  *firefox3
#  *safariproxy
#  *googlechrome
#  *konqueror
#  *firefox2
#  *safari
#  *piiexplore
#  *firefoxchrome
#  *opera
#  *iehta
#  *custom
